<?php
/**
 * Implements hook_theme().
 */
function donation_theme($existing, $type, $theme, $path) {
  return [
    'commerce_order_receipt' => [
      'template' => 'my-module-order-receipt',
      'base hook' => 'commerce_order_receipt',
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 */
function donation_views_pre_render(&$view) {
    echo "<pre>";print_r($view->result);
  if ($view->id() == 'donation') {
    foreach ($view->result as &$row) {
        var_dump($row);
     
    }
  }
}
?>
